# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  TGL_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  TGL_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad TGL

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Glad

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C TGL/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C TGL/vendor/Glad -f Makefile config=$(Glad_config)
endif

TGL: GLFW Glad
ifneq (,$(TGL_config))
	@echo "==== Building TGL ($(TGL_config)) ===="
	@${MAKE} --no-print-directory -C TGL -f Makefile config=$(TGL_config)
endif

clean:
	@${MAKE} --no-print-directory -C TGL/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C TGL/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C TGL -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   TGL"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"